version: '3.8'

services:
  api:
    build: ./api  # Directorio donde está tu Dockerfile de la API
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - prex-network

  agent:
    build: ./agent  # Directorio donde está tu Dockerfile del Agente
    volumes:
      - ./agent:/app
    networks:
      - prex-network

networks:
  prex-network:
    driver: bridge
